version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  newman-collection-run-env:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run:
          name: Get collections
          command: |
              apk add --update curl
              echo $COLLECTIONS | tr ';' '\n' | grep -v "^$" | while read COLLECTION; do curl -s https://api.getpostman.com/collections/$COLLECTION?apikey=$API_KEY >> collections.json; done
              cat collections.json

#      - newman/newman-run:
#          collection: https://api.getpostman.com/collections/$CURRENT_COLLECTIONS1?apikey=$API_KEY
#          environment: https://api.getpostman.com/environments/$CURRENT_ENV1?apikey=$API_KEY

workflows:
  version: 2
  Some Random Workflow:
    jobs:
      - newman-collection-run-env
