version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  newman-collection-run-env:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run:
          name: Get collections
          command: |
              apk add --update -q curl jq && npm config set unsafe-perm true && npm install postman-combine -g && mkdir -p collections
              curl https://api.getpostman.com/collections/14096194-1c865cca-b720-4d78-9a6d-0945faadb18e -H "X-API-Key: PMAK-60226173af8f080031e16f04-bd3d4aefcae9f39ea2f19a9a40230b1833" | jq -c '.collection' > collections/111.json
              curl https://api.getpostman.com/collections/14096194-6b5bba21-cb72-4cb9-9556-166991de37ff -H "X-API-Key: PMAK-60226173af8f080031e16f04-bd3d4aefcae9f39ea2f19a9a40230b1833" | jq -c '.collection' > collections/222.json
              postman-combine -dest ./coll.json -d collections
#              curl -s https://api.getpostman.com/environments/$CURRENT_ENV1?apikey=$API_KEY -o env.json
      - newman/newman-run:
           collection: ./coll.json
           environment: https://api.getpostman.com/environments/$CURRENT_ENV1?apikey=$API_KEY

workflows:
  version: 2
  Some Random Workflow:
    jobs:
      - newman-collection-run-env
