version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  newman-collection-run:
#    parameters:
#      environms:
#        description: project environments
#        default: "'14096194-232d230d-7d84-4e62-840e-276098f18a42' '14096194-747dceb4-778a-4653-9566-22572ff9c169'"
#        type: string
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run:
          name: Get collections
          command: echo "$CURRENT_COLLECTIONS"
#      - newman/newman-run:
#          collection: https://api.getpostman.com/collections/$CURRENT_COLLECTIONS1?apikey=$API_KEY
#          environment: https://api.getpostman.com/environments/$CURRENT_ENV1?apikey=$API_KEY

workflows:
  version: 2
  Some Random Workflow:
    jobs:
      - newman-collection-run
