version: 2.1
orbs:
  newman: postman/newman@1.0.0
jobs:
  newman-collection-run-env:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run:
          name: Get collections
          command: |
              apk add --update curl
              echo $CURRENT_COLLECTIONS | tr ';' '\n'
              cat collections.json
              curl -s https://api.getpostman.com/collections/$COLLECTION?apikey=$API_KEY

#      - newman/newman-run:
#          collection: https://api.getpostman.com/collections/$CURRENT_COLLECTIONS1?apikey=$API_KEY
#          environment: https://api.getpostman.com/environments/$CURRENT_ENV1?apikey=$API_KEY

workflows:
  version: 2
  Some Random Workflow:
    jobs:
      - newman-collection-run
