# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  newman: postman/newman@0.0.2
# 
jobs:
  newman-collection-run:
    parameters:
      envs:
        description: project environments
        default: "dev test stage prod"
        type: string
    executor: newman/postman-newman-docker
    steps:      
      - checkout
      - run:
          name: Validate terraform code
          command: |
            printf "Validating terraform code\n"
            for i in <<parameters.envs>>; do
               echo "test: $i"
            done
      - newman/newman-run:
          collection: https://api.getpostman.com/collections/14096194-232d230d-7d84-4e62-840e-276098f18a42?apikey=PMAK-60114e5616781300515026ea-3880a4a028557edf774fbb4d0a705088a0 --environment https://api.getpostman.com/environments/14096194-0aa36cea-54f6-4110-839c-8c6f34d21221?apikey=PMAK-60114e5616781300515026ea-3880a4a028557edf774fbb4d0a705088a0
          
# Orchestrate or schedule a set of jobs
workflows:
  version: 2
  Some Random Workflow:
    jobs:
      - newman-collection-run  
      
