version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  newman-collection-env:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run:
          name: Sequential collections run
          command: |
              apk add -uq curl jq
              ENV_ID=`curl https://api.getpostman.com/environments?apikey=$API_KEY | jq '.environments[] | select(.name=="$ENV")' | jq '.id'`
              echo $COLLECTIONS | tr ';' '\n' | while read COLL_NAME
              do
                  COLL_ID=$(curl -s https://api.getpostman.com/collections?apikey=$API_KEY | jq -r --arg COLL_NAME "$COLL_NAME" '.collections[] | select(.name==$COLL_NAME) | .id')
                  echo newman run https://api.getpostman.com/collections/$COLL_ID?apikey=$API_KEY --environment https://api.getpostman.com/environments/$ENV_ID?apikey=$API_KEY
              done

workflows:
  version: 2
  Some Random Workflow:
    jobs:
      - newman-collection-env






