version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  newman-collection-run-env:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run:
          name: Get collections
          command: |
              apk add --update -q curl && npm config set unsafe-perm true && npm install postman-combine -g && mkdir -p collections
              npm -v
              echo $COLLECTIONS | tr ';' '\n' | grep -v "^$" | while read COLLECTION; do curl -s https://api.getpostman.com/collections/$COLLECTION?apikey=$API_KEY -o collections/$$.json; done
              curl -s https://api.getpostman.com/environments/$COLLECTIONS?apikey=$API_KEY -o env.json
              postman-combine -h
              postman-combine -dest ./collection.json -d ./collections
#              curl -s https://api.getpostman.com/environments/$CURRENT_ENV1?apikey=$API_KEY -o env.json
#              ls -la
#      - newman/newman-run:
#           collection: run-collections-in-directory.js
#           environment: ./env.json

workflows:
  version: 2
  Some Random Workflow:
    jobs:
      - newman-collection-run-env
