version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  newman-collection-env:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run:
          name: 
          command: |
              for COLL_ID in `echo $COLLECTIONS | tr ';' '\n'`
              do
                  newman run https://api.getpostman.com/collections/$COLL_ID?apikey=$API_KEY --environment https://api.getpostman.com/environments/$ENV_ID?apikey=$API_KEY
              done
workflows:
  version: 2
  Some Random Workflow:
    jobs:
      - newman-collection-env
